#!/bin/bash
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
	curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR;
else
	php $OPENSHIFT_DATA_DIR/composer.phar self-update;
fi

cd $OPENSHIFT_REPO_DIR/laravel;
export HOME_ORIGIN=$HOME;
export HOME=$OPENSHIFT_REPO_DIR;

php $OPENSHIFT_DATA_DIR/composer.phar install;

export HOME=$HOME_ORIGIN;
