#!/bin/bash
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
	curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR;
else
	php $OPENSHIFT_DATA_DIR/composer.phar self-update;
fi

cd $OPENSHIFT_REPO_DIR/laravel;
#composer uses the home variable internally. So set it to repo dir
export HOME_ORIGIN=$HOME;
export HOME=$OPENSHIFT_REPO_DIR;

#we are in laravel dir..Do the install. Turn off progress bars, do not download and require-dev stuff and only get dist
php $OPENSHIFT_DATA_DIR/composer.phar install --no-progress --no-dev --prefer-dist;

#restore home variable to what it was
export HOME=$HOME_ORIGIN;
